-- Generated by scripts/generate-gamevars.js; do not edit.
module ShortestPath.GameVars.Varbits
  ( mdaughterQuestVar
  , dwarfrockQuest
  , golemA
  , icsLittleVar
  , togJunaBowl
  , zogre
  , thzfeBlockingBarricade
  , lostTribeQuest
  , lostTribeHole2Dug
  , edgevilleSpawn
  , faladorSpawn
  , swansong
  , pohHouseLocation
  , myq3MainQuest
  , zepMultiBasket
  , zepMultiPiccard
  , zepMultiCast
  , zepMultiGno
  , zepMultiCraft
  , zepMultiVarr
  , barbassaultArenanewb
  , frisQuest
  , atjunMedReward
  , atjunHardDone
  , vmKudos
  , dragonslayerCrandorFoundSecretDoor
  , brutFire
  , camelotSpawn
  , spellbook
  , fenkBuiltBridgeNorth
  , ardougneDiaryEasyComplete
  , ardougneDiaryMediumComplete
  , ardougneDiaryHardComplete
  , ardougneDiaryEliteComplete
  , faladorDiaryEasyComplete
  , faladorDiaryHardComplete
  , faladorDiaryEliteComplete
  , wildernessDiaryMediumComplete
  , wildernessDiaryHardComplete
  , wildernessDiaryEliteComplete
  , westernDiaryHardComplete
  , westernDiaryEliteComplete
  , kandarinDiaryHardComplete
  , kandarinDiaryEliteComplete
  , varrockDiaryMediumComplete
  , varrockDiaryEliteComplete
  , desertDiaryHardComplete
  , desertDiaryEliteComplete
  , morytaniaDiaryEasyComplete
  , morytaniaDiaryMediumComplete
  , morytaniaDiaryHardComplete
  , morytaniaDiaryEliteComplete
  , fremennikDiaryEasyComplete
  , fremennikDiaryHardComplete
  , fremennikDiaryEliteComplete
  , lumbridgeDiaryMediumComplete
  , lumbridgeDiaryHardComplete
  , lumbridgeDiaryEliteComplete
  , wildernessSwordLastTeleport
  , morytaniaLegsLastTeleport
  , yanilleTeleportLocation
  , lumbridgeCabbageTeleport
  , desertNardahTeleport
  , seersCamelotTeleport
  , seersSherlockTeleport
  , westernPiscTeleport
  , karamjaDiaryEliteComplete
  , varrockGeTeleport
  , pohTeleToggle
  , chinchompaTeleports
  , fremennikBasicTeleport
  , fenkBuiltBridgeSouth
  , cataHole1
  , cataHole2
  , raidsGuideTravelUnlock
  , veosProgress
  , karamDungeonEntryfee
  , karamDungeonBackdoor
  , bookofscrollsNardah
  , bookofscrollsDigsite
  , bookofscrollsFeldip
  , bookofscrollsLunarisle
  , bookofscrollsMortton
  , bookofscrollsPestcontrol
  , bookofscrollsPiscatoris
  , bookofscrollsTaibwo
  , bookofscrollsElf
  , bookofscrollsMosles
  , bookofscrollsLumberyard
  , bookofscrollsZulandra
  , bookofscrollsCerberus
  , observatoryShortcutRope
  , hosidiusquest
  , hosidiusquestReward
  , veosMemoirCharges
  , piscquestReward
  , bookofscrollsRevenants
  , ardougneCloakLowbits
  , corsairCoveResourceEntry
  , lumbridgeMedCount
  , shayzienquestReward
  , my2armStatus
  , myq5
  , lovaquest
  , lovaquestReward
  , arcquestReward
  , kourendDiaryEasyComplete
  , kourendDiaryMediumComplete
  , kourendDiaryHardComplete
  , kourendDiaryEliteComplete
  , zeahBlessingWoodlandTeleport
  , zeahBlessingBrimstoneTeleport
  , bookofscrollsWatsonLowbits
  , hosdunWestDoorStatus
  , hosdunEastDoorStatus
  , civitasSpawn
  , darkmShortcutInner
  , darkmShortcutOuter
  , wildernessSpawn
  , pendantOfAtesDarkfrostFound
  , pendantOfAtesTwilightFound
  , pendantOfAtesRalosFound
  , pendantOfAtesAldarinFound
  , tapoyauikRuinsFailedWallslide
  , tapoyauikFailedSteppingStones
  , colosseumHighestWave
  , kourendSpawn
  , cataHoleGiantsDen
  , lotg
  , pharaohsSceptreNecropolis
  , bcs
  , metAuburnMountainGuide
  , amenityRowboatVatrachos
  , amenityRowboatAnglers
  , amenityRowboatSoulTear
  , amenityRowboatYnysdail
  , amenityRowboatBuccaneers
  , varbitName
  ) where

import qualified Data.Map.Strict as Map
import ShortestPath.GameVars (VarbitId(..))

mdaughterQuestVar :: VarbitId
mdaughterQuestVar = VarbitId 260
dwarfrockQuest :: VarbitId
dwarfrockQuest = VarbitId 299
golemA :: VarbitId
golemA = VarbitId 346
icsLittleVar :: VarbitId
icsLittleVar = VarbitId 418
togJunaBowl :: VarbitId
togJunaBowl = VarbitId 451
zogre :: VarbitId
zogre = VarbitId 487
thzfeBlockingBarricade :: VarbitId
thzfeBlockingBarricade = VarbitId 496
lostTribeQuest :: VarbitId
lostTribeQuest = VarbitId 532
lostTribeHole2Dug :: VarbitId
lostTribeHole2Dug = VarbitId 538
edgevilleSpawn :: VarbitId
edgevilleSpawn = VarbitId 621
faladorSpawn :: VarbitId
faladorSpawn = VarbitId 668
swansong :: VarbitId
swansong = VarbitId 2098
pohHouseLocation :: VarbitId
pohHouseLocation = VarbitId 2187
myq3MainQuest :: VarbitId
myq3MainQuest = VarbitId 2573
zepMultiBasket :: VarbitId
zepMultiBasket = VarbitId 2867
zepMultiPiccard :: VarbitId
zepMultiPiccard = VarbitId 2868
zepMultiCast :: VarbitId
zepMultiCast = VarbitId 2869
zepMultiGno :: VarbitId
zepMultiGno = VarbitId 2870
zepMultiCraft :: VarbitId
zepMultiCraft = VarbitId 2871
zepMultiVarr :: VarbitId
zepMultiVarr = VarbitId 2872
barbassaultArenanewb :: VarbitId
barbassaultArenanewb = VarbitId 3264
frisQuest :: VarbitId
frisQuest = VarbitId 3311
atjunMedReward :: VarbitId
atjunMedReward = VarbitId 3598
atjunHardDone :: VarbitId
atjunHardDone = VarbitId 3611
vmKudos :: VarbitId
vmKudos = VarbitId 3637
dragonslayerCrandorFoundSecretDoor :: VarbitId
dragonslayerCrandorFoundSecretDoor = VarbitId 3741
brutFire :: VarbitId
brutFire = VarbitId 3759
camelotSpawn :: VarbitId
camelotSpawn = VarbitId 3910
spellbook :: VarbitId
spellbook = VarbitId 4070
fenkBuiltBridgeNorth :: VarbitId
fenkBuiltBridgeNorth = VarbitId 4441
ardougneDiaryEasyComplete :: VarbitId
ardougneDiaryEasyComplete = VarbitId 4458
ardougneDiaryMediumComplete :: VarbitId
ardougneDiaryMediumComplete = VarbitId 4459
ardougneDiaryHardComplete :: VarbitId
ardougneDiaryHardComplete = VarbitId 4460
ardougneDiaryEliteComplete :: VarbitId
ardougneDiaryEliteComplete = VarbitId 4461
faladorDiaryEasyComplete :: VarbitId
faladorDiaryEasyComplete = VarbitId 4462
faladorDiaryHardComplete :: VarbitId
faladorDiaryHardComplete = VarbitId 4464
faladorDiaryEliteComplete :: VarbitId
faladorDiaryEliteComplete = VarbitId 4465
wildernessDiaryMediumComplete :: VarbitId
wildernessDiaryMediumComplete = VarbitId 4467
wildernessDiaryHardComplete :: VarbitId
wildernessDiaryHardComplete = VarbitId 4468
wildernessDiaryEliteComplete :: VarbitId
wildernessDiaryEliteComplete = VarbitId 4469
westernDiaryHardComplete :: VarbitId
westernDiaryHardComplete = VarbitId 4473
westernDiaryEliteComplete :: VarbitId
westernDiaryEliteComplete = VarbitId 4474
kandarinDiaryHardComplete :: VarbitId
kandarinDiaryHardComplete = VarbitId 4477
kandarinDiaryEliteComplete :: VarbitId
kandarinDiaryEliteComplete = VarbitId 4478
varrockDiaryMediumComplete :: VarbitId
varrockDiaryMediumComplete = VarbitId 4480
varrockDiaryEliteComplete :: VarbitId
varrockDiaryEliteComplete = VarbitId 4482
desertDiaryHardComplete :: VarbitId
desertDiaryHardComplete = VarbitId 4485
desertDiaryEliteComplete :: VarbitId
desertDiaryEliteComplete = VarbitId 4486
morytaniaDiaryEasyComplete :: VarbitId
morytaniaDiaryEasyComplete = VarbitId 4487
morytaniaDiaryMediumComplete :: VarbitId
morytaniaDiaryMediumComplete = VarbitId 4488
morytaniaDiaryHardComplete :: VarbitId
morytaniaDiaryHardComplete = VarbitId 4489
morytaniaDiaryEliteComplete :: VarbitId
morytaniaDiaryEliteComplete = VarbitId 4490
fremennikDiaryEasyComplete :: VarbitId
fremennikDiaryEasyComplete = VarbitId 4491
fremennikDiaryHardComplete :: VarbitId
fremennikDiaryHardComplete = VarbitId 4493
fremennikDiaryEliteComplete :: VarbitId
fremennikDiaryEliteComplete = VarbitId 4494
lumbridgeDiaryMediumComplete :: VarbitId
lumbridgeDiaryMediumComplete = VarbitId 4496
lumbridgeDiaryHardComplete :: VarbitId
lumbridgeDiaryHardComplete = VarbitId 4497
lumbridgeDiaryEliteComplete :: VarbitId
lumbridgeDiaryEliteComplete = VarbitId 4498
wildernessSwordLastTeleport :: VarbitId
wildernessSwordLastTeleport = VarbitId 4541
morytaniaLegsLastTeleport :: VarbitId
morytaniaLegsLastTeleport = VarbitId 4542
yanilleTeleportLocation :: VarbitId
yanilleTeleportLocation = VarbitId 4548
lumbridgeCabbageTeleport :: VarbitId
lumbridgeCabbageTeleport = VarbitId 4552
desertNardahTeleport :: VarbitId
desertNardahTeleport = VarbitId 4558
seersCamelotTeleport :: VarbitId
seersCamelotTeleport = VarbitId 4560
seersSherlockTeleport :: VarbitId
seersSherlockTeleport = VarbitId 4561
westernPiscTeleport :: VarbitId
westernPiscTeleport = VarbitId 4564
karamjaDiaryEliteComplete :: VarbitId
karamjaDiaryEliteComplete = VarbitId 4566
varrockGeTeleport :: VarbitId
varrockGeTeleport = VarbitId 4585
pohTeleToggle :: VarbitId
pohTeleToggle = VarbitId 4744
chinchompaTeleports :: VarbitId
chinchompaTeleports = VarbitId 4819
fremennikBasicTeleport :: VarbitId
fremennikBasicTeleport = VarbitId 5005
fenkBuiltBridgeSouth :: VarbitId
fenkBuiltBridgeSouth = VarbitId 5023
cataHole1 :: VarbitId
cataHole1 = VarbitId 5087
cataHole2 :: VarbitId
cataHole2 = VarbitId 5088
raidsGuideTravelUnlock :: VarbitId
raidsGuideTravelUnlock = VarbitId 5421
veosProgress :: VarbitId
veosProgress = VarbitId 5619
karamDungeonEntryfee :: VarbitId
karamDungeonEntryfee = VarbitId 5628
karamDungeonBackdoor :: VarbitId
karamDungeonBackdoor = VarbitId 5629
bookofscrollsNardah :: VarbitId
bookofscrollsNardah = VarbitId 5672
bookofscrollsDigsite :: VarbitId
bookofscrollsDigsite = VarbitId 5673
bookofscrollsFeldip :: VarbitId
bookofscrollsFeldip = VarbitId 5674
bookofscrollsLunarisle :: VarbitId
bookofscrollsLunarisle = VarbitId 5675
bookofscrollsMortton :: VarbitId
bookofscrollsMortton = VarbitId 5676
bookofscrollsPestcontrol :: VarbitId
bookofscrollsPestcontrol = VarbitId 5677
bookofscrollsPiscatoris :: VarbitId
bookofscrollsPiscatoris = VarbitId 5678
bookofscrollsTaibwo :: VarbitId
bookofscrollsTaibwo = VarbitId 5679
bookofscrollsElf :: VarbitId
bookofscrollsElf = VarbitId 5680
bookofscrollsMosles :: VarbitId
bookofscrollsMosles = VarbitId 5681
bookofscrollsLumberyard :: VarbitId
bookofscrollsLumberyard = VarbitId 5682
bookofscrollsZulandra :: VarbitId
bookofscrollsZulandra = VarbitId 5683
bookofscrollsCerberus :: VarbitId
bookofscrollsCerberus = VarbitId 5684
observatoryShortcutRope :: VarbitId
observatoryShortcutRope = VarbitId 5810
hosidiusquest :: VarbitId
hosidiusquest = VarbitId 6027
hosidiusquestReward :: VarbitId
hosidiusquestReward = VarbitId 6028
veosMemoirCharges :: VarbitId
veosMemoirCharges = VarbitId 6035
piscquestReward :: VarbitId
piscquestReward = VarbitId 6038
bookofscrollsRevenants :: VarbitId
bookofscrollsRevenants = VarbitId 6056
ardougneCloakLowbits :: VarbitId
ardougneCloakLowbits = VarbitId 6069
corsairCoveResourceEntry :: VarbitId
corsairCoveResourceEntry = VarbitId 6076
lumbridgeMedCount :: VarbitId
lumbridgeMedCount = VarbitId 6312
shayzienquestReward :: VarbitId
shayzienquestReward = VarbitId 6359
my2armStatus :: VarbitId
my2armStatus = VarbitId 6528
myq5 :: VarbitId
myq5 = VarbitId 7255
lovaquest :: VarbitId
lovaquest = VarbitId 7796
lovaquestReward :: VarbitId
lovaquestReward = VarbitId 7801
arcquestReward :: VarbitId
arcquestReward = VarbitId 7857
kourendDiaryEasyComplete :: VarbitId
kourendDiaryEasyComplete = VarbitId 7925
kourendDiaryMediumComplete :: VarbitId
kourendDiaryMediumComplete = VarbitId 7926
kourendDiaryHardComplete :: VarbitId
kourendDiaryHardComplete = VarbitId 7927
kourendDiaryEliteComplete :: VarbitId
kourendDiaryEliteComplete = VarbitId 7928
zeahBlessingWoodlandTeleport :: VarbitId
zeahBlessingWoodlandTeleport = VarbitId 7937
zeahBlessingBrimstoneTeleport :: VarbitId
zeahBlessingBrimstoneTeleport = VarbitId 7938
bookofscrollsWatsonLowbits :: VarbitId
bookofscrollsWatsonLowbits = VarbitId 8253
hosdunWestDoorStatus :: VarbitId
hosdunWestDoorStatus = VarbitId 8397
hosdunEastDoorStatus :: VarbitId
hosdunEastDoorStatus = VarbitId 8398
civitasSpawn :: VarbitId
civitasSpawn = VarbitId 9805
darkmShortcutInner :: VarbitId
darkmShortcutInner = VarbitId 10449
darkmShortcutOuter :: VarbitId
darkmShortcutOuter = VarbitId 10450
wildernessSpawn :: VarbitId
wildernessSpawn = VarbitId 10528
pendantOfAtesDarkfrostFound :: VarbitId
pendantOfAtesDarkfrostFound = VarbitId 11175
pendantOfAtesTwilightFound :: VarbitId
pendantOfAtesTwilightFound = VarbitId 11176
pendantOfAtesRalosFound :: VarbitId
pendantOfAtesRalosFound = VarbitId 11177
pendantOfAtesAldarinFound :: VarbitId
pendantOfAtesAldarinFound = VarbitId 11178
tapoyauikRuinsFailedWallslide :: VarbitId
tapoyauikRuinsFailedWallslide = VarbitId 11179
tapoyauikFailedSteppingStones :: VarbitId
tapoyauikFailedSteppingStones = VarbitId 11180
colosseumHighestWave :: VarbitId
colosseumHighestWave = VarbitId 11410
kourendSpawn :: VarbitId
kourendSpawn = VarbitId 12310
cataHoleGiantsDen :: VarbitId
cataHoleGiantsDen = VarbitId 12341
lotg :: VarbitId
lotg = VarbitId 13599
pharaohsSceptreNecropolis :: VarbitId
pharaohsSceptreNecropolis = VarbitId 13839
bcs :: VarbitId
bcs = VarbitId 13841
metAuburnMountainGuide :: VarbitId
metAuburnMountainGuide = VarbitId 17226
amenityRowboatVatrachos :: VarbitId
amenityRowboatVatrachos = VarbitId 18351
amenityRowboatAnglers :: VarbitId
amenityRowboatAnglers = VarbitId 18355
amenityRowboatSoulTear :: VarbitId
amenityRowboatSoulTear = VarbitId 18356
amenityRowboatYnysdail :: VarbitId
amenityRowboatYnysdail = VarbitId 18370
amenityRowboatBuccaneers :: VarbitId
amenityRowboatBuccaneers = VarbitId 18371

varbitName :: VarbitId -> Maybe String
varbitName value = Map.lookup value names

names :: Map.Map VarbitId String
names = Map.fromList
  [ (mdaughterQuestVar, "MDAUGHTER_QUEST_VAR")
  , (dwarfrockQuest, "DWARFROCK_QUEST")
  , (golemA, "GOLEM_A")
  , (icsLittleVar, "ICS_LITTLE_VAR")
  , (togJunaBowl, "TOG_JUNA_BOWL")
  , (zogre, "ZOGRE")
  , (thzfeBlockingBarricade, "THZFE_BLOCKING_BARRICADE")
  , (lostTribeQuest, "LOST_TRIBE_QUEST")
  , (lostTribeHole2Dug, "LOST_TRIBE_HOLE_2_DUG")
  , (edgevilleSpawn, "EDGEVILLE_SPAWN")
  , (faladorSpawn, "FALADOR_SPAWN")
  , (swansong, "SWANSONG")
  , (pohHouseLocation, "POH_HOUSE_LOCATION")
  , (myq3MainQuest, "MYQ3_MAIN_QUEST")
  , (zepMultiBasket, "ZEP_MULTI_BASKET")
  , (zepMultiPiccard, "ZEP_MULTI_PICCARD")
  , (zepMultiCast, "ZEP_MULTI_CAST")
  , (zepMultiGno, "ZEP_MULTI_GNO")
  , (zepMultiCraft, "ZEP_MULTI_CRAFT")
  , (zepMultiVarr, "ZEP_MULTI_VARR")
  , (barbassaultArenanewb, "BARBASSAULT_ARENANEWB")
  , (frisQuest, "FRIS_QUEST")
  , (atjunMedReward, "ATJUN_MED_REWARD")
  , (atjunHardDone, "ATJUN_HARD_DONE")
  , (vmKudos, "VM_KUDOS")
  , (dragonslayerCrandorFoundSecretDoor, "DRAGONSLAYER_CRANDOR_FOUND_SECRET_DOOR")
  , (brutFire, "BRUT_FIRE")
  , (camelotSpawn, "CAMELOT_SPAWN")
  , (spellbook, "SPELLBOOK")
  , (fenkBuiltBridgeNorth, "FENK_BUILT_BRIDGE_NORTH")
  , (ardougneDiaryEasyComplete, "ARDOUGNE_DIARY_EASY_COMPLETE")
  , (ardougneDiaryMediumComplete, "ARDOUGNE_DIARY_MEDIUM_COMPLETE")
  , (ardougneDiaryHardComplete, "ARDOUGNE_DIARY_HARD_COMPLETE")
  , (ardougneDiaryEliteComplete, "ARDOUGNE_DIARY_ELITE_COMPLETE")
  , (faladorDiaryEasyComplete, "FALADOR_DIARY_EASY_COMPLETE")
  , (faladorDiaryHardComplete, "FALADOR_DIARY_HARD_COMPLETE")
  , (faladorDiaryEliteComplete, "FALADOR_DIARY_ELITE_COMPLETE")
  , (wildernessDiaryMediumComplete, "WILDERNESS_DIARY_MEDIUM_COMPLETE")
  , (wildernessDiaryHardComplete, "WILDERNESS_DIARY_HARD_COMPLETE")
  , (wildernessDiaryEliteComplete, "WILDERNESS_DIARY_ELITE_COMPLETE")
  , (westernDiaryHardComplete, "WESTERN_DIARY_HARD_COMPLETE")
  , (westernDiaryEliteComplete, "WESTERN_DIARY_ELITE_COMPLETE")
  , (kandarinDiaryHardComplete, "KANDARIN_DIARY_HARD_COMPLETE")
  , (kandarinDiaryEliteComplete, "KANDARIN_DIARY_ELITE_COMPLETE")
  , (varrockDiaryMediumComplete, "VARROCK_DIARY_MEDIUM_COMPLETE")
  , (varrockDiaryEliteComplete, "VARROCK_DIARY_ELITE_COMPLETE")
  , (desertDiaryHardComplete, "DESERT_DIARY_HARD_COMPLETE")
  , (desertDiaryEliteComplete, "DESERT_DIARY_ELITE_COMPLETE")
  , (morytaniaDiaryEasyComplete, "MORYTANIA_DIARY_EASY_COMPLETE")
  , (morytaniaDiaryMediumComplete, "MORYTANIA_DIARY_MEDIUM_COMPLETE")
  , (morytaniaDiaryHardComplete, "MORYTANIA_DIARY_HARD_COMPLETE")
  , (morytaniaDiaryEliteComplete, "MORYTANIA_DIARY_ELITE_COMPLETE")
  , (fremennikDiaryEasyComplete, "FREMENNIK_DIARY_EASY_COMPLETE")
  , (fremennikDiaryHardComplete, "FREMENNIK_DIARY_HARD_COMPLETE")
  , (fremennikDiaryEliteComplete, "FREMENNIK_DIARY_ELITE_COMPLETE")
  , (lumbridgeDiaryMediumComplete, "LUMBRIDGE_DIARY_MEDIUM_COMPLETE")
  , (lumbridgeDiaryHardComplete, "LUMBRIDGE_DIARY_HARD_COMPLETE")
  , (lumbridgeDiaryEliteComplete, "LUMBRIDGE_DIARY_ELITE_COMPLETE")
  , (wildernessSwordLastTeleport, "WILDERNESS_SWORD_LAST_TELEPORT")
  , (morytaniaLegsLastTeleport, "MORYTANIA_LEGS_LAST_TELEPORT")
  , (yanilleTeleportLocation, "YANILLE_TELEPORT_LOCATION")
  , (lumbridgeCabbageTeleport, "LUMBRIDGE_CABBAGE_TELEPORT")
  , (desertNardahTeleport, "DESERT_NARDAH_TELEPORT")
  , (seersCamelotTeleport, "SEERS_CAMELOT_TELEPORT")
  , (seersSherlockTeleport, "SEERS_SHERLOCK_TELEPORT")
  , (westernPiscTeleport, "WESTERN_PISC_TELEPORT")
  , (karamjaDiaryEliteComplete, "KARAMJA_DIARY_ELITE_COMPLETE")
  , (varrockGeTeleport, "VARROCK_GE_TELEPORT")
  , (pohTeleToggle, "POH_TELE_TOGGLE")
  , (chinchompaTeleports, "CHINCHOMPA_TELEPORTS")
  , (fremennikBasicTeleport, "FREMENNIK_BASIC_TELEPORT")
  , (fenkBuiltBridgeSouth, "FENK_BUILT_BRIDGE_SOUTH")
  , (cataHole1, "CATA_HOLE1")
  , (cataHole2, "CATA_HOLE2")
  , (raidsGuideTravelUnlock, "RAIDS_GUIDE_TRAVEL_UNLOCK")
  , (veosProgress, "VEOS_PROGRESS")
  , (karamDungeonEntryfee, "KARAM_DUNGEON_ENTRYFEE")
  , (karamDungeonBackdoor, "KARAM_DUNGEON_BACKDOOR")
  , (bookofscrollsNardah, "BOOKOFSCROLLS_NARDAH")
  , (bookofscrollsDigsite, "BOOKOFSCROLLS_DIGSITE")
  , (bookofscrollsFeldip, "BOOKOFSCROLLS_FELDIP")
  , (bookofscrollsLunarisle, "BOOKOFSCROLLS_LUNARISLE")
  , (bookofscrollsMortton, "BOOKOFSCROLLS_MORTTON")
  , (bookofscrollsPestcontrol, "BOOKOFSCROLLS_PESTCONTROL")
  , (bookofscrollsPiscatoris, "BOOKOFSCROLLS_PISCATORIS")
  , (bookofscrollsTaibwo, "BOOKOFSCROLLS_TAIBWO")
  , (bookofscrollsElf, "BOOKOFSCROLLS_ELF")
  , (bookofscrollsMosles, "BOOKOFSCROLLS_MOSLES")
  , (bookofscrollsLumberyard, "BOOKOFSCROLLS_LUMBERYARD")
  , (bookofscrollsZulandra, "BOOKOFSCROLLS_ZULANDRA")
  , (bookofscrollsCerberus, "BOOKOFSCROLLS_CERBERUS")
  , (observatoryShortcutRope, "OBSERVATORY_SHORTCUT_ROPE")
  , (hosidiusquest, "HOSIDIUSQUEST")
  , (hosidiusquestReward, "HOSIDIUSQUEST_REWARD")
  , (veosMemoirCharges, "VEOS_MEMOIR_CHARGES")
  , (piscquestReward, "PISCQUEST_REWARD")
  , (bookofscrollsRevenants, "BOOKOFSCROLLS_REVENANTS")
  , (ardougneCloakLowbits, "ARDOUGNE_CLOAK_LOWBITS")
  , (corsairCoveResourceEntry, "CORSAIR_COVE_RESOURCE_ENTRY")
  , (lumbridgeMedCount, "LUMBRIDGE_MED_COUNT")
  , (shayzienquestReward, "SHAYZIENQUEST_REWARD")
  , (my2armStatus, "MY2ARM_STATUS")
  , (myq5, "MYQ5")
  , (lovaquest, "LOVAQUEST")
  , (lovaquestReward, "LOVAQUEST_REWARD")
  , (arcquestReward, "ARCQUEST_REWARD")
  , (kourendDiaryEasyComplete, "KOUREND_DIARY_EASY_COMPLETE")
  , (kourendDiaryMediumComplete, "KOUREND_DIARY_MEDIUM_COMPLETE")
  , (kourendDiaryHardComplete, "KOUREND_DIARY_HARD_COMPLETE")
  , (kourendDiaryEliteComplete, "KOUREND_DIARY_ELITE_COMPLETE")
  , (zeahBlessingWoodlandTeleport, "ZEAH_BLESSING_WOODLAND_TELEPORT")
  , (zeahBlessingBrimstoneTeleport, "ZEAH_BLESSING_BRIMSTONE_TELEPORT")
  , (bookofscrollsWatsonLowbits, "BOOKOFSCROLLS_WATSON_LOWBITS")
  , (hosdunWestDoorStatus, "HOSDUN_WEST_DOOR_STATUS")
  , (hosdunEastDoorStatus, "HOSDUN_EAST_DOOR_STATUS")
  , (civitasSpawn, "CIVITAS_SPAWN")
  , (darkmShortcutInner, "DARKM_SHORTCUT_INNER")
  , (darkmShortcutOuter, "DARKM_SHORTCUT_OUTER")
  , (wildernessSpawn, "WILDERNESS_SPAWN")
  , (pendantOfAtesDarkfrostFound, "PENDANT_OF_ATES_DARKFROST_FOUND")
  , (pendantOfAtesTwilightFound, "PENDANT_OF_ATES_TWILIGHT_FOUND")
  , (pendantOfAtesRalosFound, "PENDANT_OF_ATES_RALOS_FOUND")
  , (pendantOfAtesAldarinFound, "PENDANT_OF_ATES_ALDARIN_FOUND")
  , (tapoyauikRuinsFailedWallslide, "TAPOYAUIK_RUINS_FAILED_WALLSLIDE")
  , (tapoyauikFailedSteppingStones, "TAPOYAUIK_FAILED_STEPPING_STONES")
  , (colosseumHighestWave, "COLOSSEUM_HIGHEST_WAVE")
  , (kourendSpawn, "KOUREND_SPAWN")
  , (cataHoleGiantsDen, "CATA_HOLE_GIANTS_DEN")
  , (lotg, "LOTG")
  , (pharaohsSceptreNecropolis, "PHARAOHS_SCEPTRE_NECROPOLIS")
  , (bcs, "BCS")
  , (metAuburnMountainGuide, "MET_AUBURN_MOUNTAIN_GUIDE")
  , (amenityRowboatVatrachos, "AMENITY_ROWBOAT_VATRACHOS")
  , (amenityRowboatAnglers, "AMENITY_ROWBOAT_ANGLERS")
  , (amenityRowboatSoulTear, "AMENITY_ROWBOAT_SOUL_TEAR")
  , (amenityRowboatYnysdail, "AMENITY_ROWBOAT_YNYSDAIL")
  , (amenityRowboatBuccaneers, "AMENITY_ROWBOAT_BUCCANEERS")
  ]
