-- Generated by scripts/generate-gamevars.js; do not edit.
module ShortestPath.GameVars.VarPlayers
  ( fishingcompo
  , haunted
  , waterfallQuest
  , treequest
  , zombiequeen
  , legendsquest
  , grandtree
  , elenaquest
  , dragonquest
  , itwatchtower
  , regicideQuest
  , miscQuest
  , mourningQuest
  , slug2Regionuid
  , aideTeleTimer
  , quetzalsUnlocked
  , homeTeleportAnimToggles
  , leagueCombatMasteryPaths
  , varPlayerName
  ) where

import qualified Data.Map.Strict as Map
import ShortestPath.GameVars (VarPlayerId(..))

fishingcompo :: VarPlayerId
fishingcompo = VarPlayerId 11
haunted :: VarPlayerId
haunted = VarPlayerId 32
waterfallQuest :: VarPlayerId
waterfallQuest = VarPlayerId 65
treequest :: VarPlayerId
treequest = VarPlayerId 111
zombiequeen :: VarPlayerId
zombiequeen = VarPlayerId 116
legendsquest :: VarPlayerId
legendsquest = VarPlayerId 139
grandtree :: VarPlayerId
grandtree = VarPlayerId 150
elenaquest :: VarPlayerId
elenaquest = VarPlayerId 165
dragonquest :: VarPlayerId
dragonquest = VarPlayerId 176
itwatchtower :: VarPlayerId
itwatchtower = VarPlayerId 212
regicideQuest :: VarPlayerId
regicideQuest = VarPlayerId 328
miscQuest :: VarPlayerId
miscQuest = VarPlayerId 359
mourningQuest :: VarPlayerId
mourningQuest = VarPlayerId 517
slug2Regionuid :: VarPlayerId
slug2Regionuid = VarPlayerId 888
aideTeleTimer :: VarPlayerId
aideTeleTimer = VarPlayerId 892
quetzalsUnlocked :: VarPlayerId
quetzalsUnlocked = VarPlayerId 4182
homeTeleportAnimToggles :: VarPlayerId
homeTeleportAnimToggles = VarPlayerId 4560
leagueCombatMasteryPaths :: VarPlayerId
leagueCombatMasteryPaths = VarPlayerId 4566

varPlayerName :: VarPlayerId -> Maybe String
varPlayerName value = Map.lookup value names

names :: Map.Map VarPlayerId String
names = Map.fromList
  [ (fishingcompo, "FISHINGCOMPO")
  , (haunted, "HAUNTED")
  , (waterfallQuest, "WATERFALL_QUEST")
  , (treequest, "TREEQUEST")
  , (zombiequeen, "ZOMBIEQUEEN")
  , (legendsquest, "LEGENDSQUEST")
  , (grandtree, "GRANDTREE")
  , (elenaquest, "ELENAQUEST")
  , (dragonquest, "DRAGONQUEST")
  , (itwatchtower, "ITWATCHTOWER")
  , (regicideQuest, "REGICIDE_QUEST")
  , (miscQuest, "MISC_QUEST")
  , (mourningQuest, "MOURNING_QUEST")
  , (slug2Regionuid, "SLUG2_REGIONUID")
  , (aideTeleTimer, "AIDE_TELE_TIMER")
  , (quetzalsUnlocked, "QUETZALS_UNLOCKED")
  , (homeTeleportAnimToggles, "HOME_TELEPORT_ANIM_TOGGLES")
  , (leagueCombatMasteryPaths, "LEAGUE_COMBAT_MASTERY_PATHS")
  ]
